// <auto-generated />
namespace CherryCitySoftware.MedicalOffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Message4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Message4));
        
        string IMigrationMetadata.Id
        {
            get { return "201410240458492_Message4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
